apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.AppName }}
  labels:
    app: {{ .Values.AppName }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.ContainerPort }}
  selector:
    app: {{ .Values.AppName }}
    
